repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # v5.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=100]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: detect-private-key
      - id: no-commit-to-branch
        args: [--branch=main]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 4924b0e01e032fea073ad04a1c5cfa7e4add0afb # v0.15.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: d2823d321df3af8f878f7ee3414dc94d037145b9 # v2.1.0
    hooks:
      - id: mypy
        additional_dependencies:
          - keyring>=23.0
          - requests>=2.20
